name: Verify Stripper Capitalization

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify Stripper Capitalization
        uses: Vauff/stripper-case-action@main
        with:
          stripper-path: stripper/
